### ISSUE TITLE
[0.7.x] NRE DysonSPhereAddNodeProcessor (client side)

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#333]
![grafik](https://user-images.githubusercontent.com/79335616/122808544-53bdac00-d2cd-11eb-8def-fde1ceea7780.png)
 Client was just flying around.

**Comment by PhantomGamers** [comment]
The error itself is fixed by https://github.com/PhantomGamers/nebula/commit/a6b2842e69c3feb2b6a72c13c02b4ab3135b7217

but why can DysonSphereLayer be null to begin with? It was null propagated before so I guess it was expected to happen, but the check below just made sure it was not 0 (which null isn't), so it proceeded and errored, now with the fix above we just return early if dsl is null.

I guess maybe because layer adding is only synced to people in the same system? Needs more investigation

**Comment by sp00ktober** [comment]
@PhantomGamers can we close this?

**Comment by PhantomGamers** [comment]
This is fixed and it seems that the fix has had no negative consequences so this seems good to close unless we get reports of issues related to Dyson Sphere syncing
