### ISSUE TITLE
[Suggest]The official game version has been updated, and the MOD has been disabled

### ISSUE THREAD

**Issue by Chowtung** [hubastard/nebula#507]
Two thousand Chinese players are looking forward to your update.XD

**Comment by m1ds** [comment]
Two thousand and two Chinese players now

**Comment by PhantomGamers** [comment]
If you have the game on Steam you can opt into the 0.8.x beta to continue playing the mod.
![image](https://user-images.githubusercontent.com/844685/150509056-4eb1e3bf-5e93-4570-8e23-63d7300fa725.png)


BTW do either of you own the game on WeGame or know anyone who does? If so, can you tell me if the WeGame version has the file `DSPGAME_Data\Plugins\steam_api64.dll`?

Because the Steam version comes with `rail_api64.dll` which I think is from WeGame

**Comment by Chowtung** [comment]
I bought a WeGame version，There is no steam_aip64.dll.

\Plugins a total of
rail_api.dll 15526kb
rail_api64.dll 19642kb
rail_wrapper.dll 1047kb
rail_wrapper64.dll 1351kb

And dbghelp.dll 1227kb this is the only difference from the Steam edition。

We look forward to using your mod in the new version as well。

**Comment by KlausNie** [comment]
@PhantomGamers 
I've just yesterday started to use this mod. Does the mod only work with the 0.8.x alpha? Or is this a workaround because a recent game update broke something?

**Comment by PhantomGamers** [comment]
> @PhantomGamers I've just yesterday started to use this mod. Does the mod only work with the 0.8.x alpha? Or is this a workaround because a recent game update broke something?

mmm I don't understand the difference between the two questions lol.

The mod only works with the 0.8.x branch until it is updated to work with the changes introduced in 0.9.x

**Comment by KlausNie** [comment]
Oh! My bad, I was under the impression that there is already a stable version of the game!

Instead 0.9.x is the latest version and the mod does not yet work with that one! Got it!

Thank you very much for the mod/work btw!

**Comment by hkmrys** [comment]
怎么加入测试版？

**Comment by itpropro** [comment]
> Two thousand and two Chinese players now

Two thousand European players are impressed by the work that has been done 😉
